name: 'Github Action Log Cleaner'
author: 'Jose Miguel Miranda'
description: 'Limpia los logs/ejecuciones generados por Github Actions en un repo'

inputs:
  num_runs:
    description: "Numero Logs/Ejeuciones que dejamos sin borrar"
    required: false
    default: 10

  myToken:
    description: "PAT Personal Access Token para borrar ejecuciones/logs"
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'delete'
  color: 'yellow'
